/**
 * Runs once when the server starts. Validates env vars for every enabled
 * module (lib/env.ts) and, if monitoring is enabled, boots Sentry for the
 * current runtime. Regenerated by scripts/setup.mjs and
 * scripts/modules/add-*.mjs — don't hand-edit, the next module script will
 * overwrite it.
 */
export async function register() {
  if (process.env.NEXT_RUNTIME === "nodejs") {
    const { validateEnv } = await import("./lib/env");
    validateEnv();
  }
}

