/**
 * Aggregates every enabled module's client-side provider. Regenerated by
 * scripts/setup.mjs and scripts/modules/add-*.mjs — don't hand-edit the
 * wrapping, since the next module script will overwrite it. Auth/analytics
 * providers only appear here when their module is enabled in
 * lib/project.config.ts.
 */
export function Providers({ children }: { children: React.ReactNode }) {
  return (
    <>
      {children}
    </>
  );
}
