// Shared helpers for scripts/setup.mjs and scripts/modules/add-*.mjs.
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { createInterface } from "node:readline/promises";
import { fileURLToPath, pathToFileURL } from "node:url";

export async function promptYesNo(question, defaultYes = false) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const suffix = defaultYes ? "(Y/n)" : "(y/N)";
  const answer = (await rl.question(`${question} ${suffix} `)).trim().toLowerCase();
  rl.close();
  if (answer === "") return defaultYes;
  return answer === "y" || answer === "yes";
}

export async function promptText(question, { defaultValue = "" } = {}) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const suffix = defaultValue ? ` [${defaultValue}]` : "";
  const answer = (await rl.question(`${question}${suffix}: `)).trim();
  rl.close();
  return answer || defaultValue;
}

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

export function path(...segments) {
  return join(ROOT, ...segments);
}

export function pnpmAdd(packages, { dev = false } = {}) {
  if (packages.length === 0) return;
  const args = ["add", ...(dev ? ["-D"] : []), ...packages];
  console.log(`  $ pnpm ${args.join(" ")}`);
  try {
    execFileSync("pnpm", args, { cwd: ROOT, stdio: "inherit", shell: true });
  } catch {
    // A freshly added package's postinstall script may be pending pnpm's
    // build-script approval gate (see pnpm-workspace.yaml). Approve
    // everything currently pending and retry once.
    console.log("  pending build scripts detected, approving and retrying...");
    execFileSync("pnpm", ["approve-builds", "--all"], { cwd: ROOT, stdio: "inherit", shell: true });
    execFileSync("pnpm", args, { cwd: ROOT, stdio: "inherit", shell: true });
  }
}

export function writeFile(relPath, content) {
  const full = path(relPath);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content, "utf8");
  console.log(`  wrote ${relPath}`);
}

export function readProjectConfig() {
  const raw = readFileSync(path("lib/project.config.ts"), "utf8");
  const modules = {};
  for (const name of ["database", "auth", "analytics", "monitoring"]) {
    const match = raw.match(new RegExp(`${name}:\\s*(true|false)`));
    modules[name] = match ? match[1] === "true" : false;
  }
  return modules;
}

export function writeProjectConfig(modules) {
  const content = `/**
 * Single source of truth for which optional modules are enabled.
 *
 * Nothing outside this file should hardcode a module's on/off state.
 * \`pnpm run setup\` and \`pnpm run add:<module>\` write to this file —
 * you generally shouldn't hand-edit it unless you're changing your mind
 * about a module after the fact.
 */
export const projectConfig = {
  modules: {
    database: ${modules.database}, // Supabase
    auth: ${modules.auth}, // Clerk
    analytics: ${modules.analytics}, // PostHog
    monitoring: ${modules.monitoring}, // Sentry
  },
} as const;

export type ModuleName = keyof typeof projectConfig.modules;
`;
  writeFile("lib/project.config.ts", content);
}

/**
 * Regenerates components/providers/providers.tsx from scratch based on the
 * currently enabled modules. Safe to call unconditionally — a disabled
 * module simply contributes nothing to the generated file.
 */
export function regenerateProvidersFile(modules) {
  const imports = [];
  const opens = [];
  const closes = [];

  if (modules.auth) {
    imports.push('import { ClerkProvider } from "@clerk/nextjs";');
    opens.push("<ClerkProvider>");
    closes.unshift("</ClerkProvider>");
  }
  if (modules.analytics) {
    imports.push('import { PostHogProvider } from "./posthog-provider";');
    opens.push("<PostHogProvider>");
    closes.unshift("</PostHogProvider>");
  }

  const body =
    opens.length === 0
      ? "{children}"
      : `${opens.join("\n      ")}\n        {children}\n      ${closes.join("\n      ")}`;

  const content = `${imports.length > 0 ? imports.join("\n") + "\n\n" : ""}/**
 * Aggregates every enabled module's client-side provider. Regenerated by
 * scripts/setup.mjs and scripts/modules/add-*.mjs — don't hand-edit the
 * wrapping, since the next module script will overwrite it. Auth/analytics
 * providers only appear here when their module is enabled in
 * lib/project.config.ts.
 */
export function Providers({ children }: { children: React.ReactNode }) {
  return (
    <>
      ${body}
    </>
  );
}
`;
  writeFile("components/providers/providers.tsx", content);
}

/**
 * Regenerates instrumentation.ts, the Next.js server-startup hook. Always
 * validates env for enabled modules; additionally boots Sentry for the
 * current runtime when monitoring is enabled. Safe to call unconditionally.
 */
export function regenerateInstrumentationFile(modules) {
  const sentryImportLine = modules.monitoring ? 'import * as Sentry from "@sentry/nextjs";\n\n' : "";
  const sentryServerImportLine = modules.monitoring
    ? '\n    await import("./sentry.server.config");'
    : "";
  const edgeBlock = modules.monitoring
    ? `

  if (process.env.NEXT_RUNTIME === "edge") {
    await import("./sentry.edge.config");
  }`
    : "";
  const onRequestErrorExport = modules.monitoring
    ? "\n\nexport const onRequestError = Sentry.captureRequestError;\n"
    : "\n";

  const content = `${sentryImportLine}/**
 * Runs once when the server starts. Validates env vars for every enabled
 * module (lib/env.ts) and, if monitoring is enabled, boots Sentry for the
 * current runtime. Regenerated by scripts/setup.mjs and
 * scripts/modules/add-*.mjs — don't hand-edit, the next module script will
 * overwrite it.
 */
export async function register() {
  if (process.env.NEXT_RUNTIME === "nodejs") {
    const { validateEnv } = await import("./lib/env");
    validateEnv();${sentryServerImportLine}
  }${edgeBlock}
}
${onRequestErrorExport}`;
  writeFile("instrumentation.ts", content);
}

export function upsertEnvLocal(values) {
  const envLocalPath = path(".env.local");
  let content = existsSync(envLocalPath) ? readFileSync(envLocalPath, "utf8") : "";
  for (const [key, value] of Object.entries(values)) {
    const line = `${key}=${value ?? ""}`;
    const re = new RegExp(`^${key}=.*$`, "m");
    if (re.test(content)) {
      content = content.replace(re, line);
    } else {
      content += (content.endsWith("\n") || content === "" ? "" : "\n") + line + "\n";
    }
  }
  writeFileSync(envLocalPath, content, "utf8");
  console.log("  updated .env.local");
}

export function isMainModule(importMetaUrl) {
  return Boolean(process.argv[1]) && importMetaUrl === pathToFileURL(process.argv[1]).href;
}
